version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: ${PROJECT_NAME}-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${PROJECT_NAME}-redis-data:/data
    networks:
      - ${PROJECT_NAME}-redis-network
    ports:
      - "6379:6379"

networks:
  ${PROJECT_NAME}-redis-network:
    driver: bridge
    name: ${PROJECT_NAME}-redis-network

volumes:
  ${PROJECT_NAME}-redis-data:
    driver: local
    name: ${PROJECT_NAME}-redis-data
